# Generated by Django 4.2.30 on 2026-10-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_market_visit',
            field=models.BooleanField(default=False, help_text='If true, user can access the Market Visit tab (Ahtisham/Aslam).'),
        ),
    ]
