# Generated by Django 4.2.30 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_market_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('order_clerk', 'Order Clerk'), ('batch_clerk', 'Batch Clerk'), ('admin', 'Admin')], default='order_clerk', max_length=32),
        ),
    ]
