# Generated by Django 4.2.30 on 2026-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_dispatch_clerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('order_clerk', 'Order Clerk'), ('batch_clerk', 'Batch Clerk'), ('dispatch_clerk', 'Dispatch Clerk'), ('loading_clerk', 'Loading Clerk'), ('admin', 'Admin')], default='order_clerk', max_length=32),
        ),
    ]
