# Generated by Django 4.2.30 on 2026-10-05 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market_visits.columns


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-updated_at'],
                'unique_together': {('created_by', 'visit_date')},
            },
        ),
        migrations.CreateModel(
            name='MarketVisitStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('availability', models.JSONField(default=market_visits.columns.empty_availability)),
                ('facing', models.JSONField(default=market_visits.columns.empty_facing)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='market_visits.marketvisit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
