# Generated by Django 4.2.30 on 2026-10-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketvisit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='marketvisit',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=16),
        ),
    ]
