# Generated by Django 4.2.30 on 2026-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_visits', '0002_alter_marketvisit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketvisit',
            name='status',
            field=models.CharField(choices=[('in_process', 'In process'), ('submitted', 'Submitted')], default='in_process', max_length=16),
        ),
    ]
