# Generated by Django 4.2.30 on 2026-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_sheet',
            field=models.BooleanField(default=True, help_text='If true, product appears on the main loading sheet'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_label',
            field=models.CharField(choices=[('bottles', 'bottles'), ('bundles', 'bundles')], default='bottles', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='bottles_per_carton',
            field=models.PositiveIntegerField(help_text='Units (bottles or bundles) packed per carton'),
        ),
    ]
