# Generated by Django 4.2.30 on 2026-10-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('catalog', '0002_product_show_on_sheet_product_unit_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_product',
            field=models.ForeignKey(blank=True, help_text='Parent brand for Esha batch assignment (Rashid portal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='batches.batchproduct'),
        ),
    ]
