# Generated by Django 4.2.30 on 2026-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_loading_clerk_and_product_batch_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_carton_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Expected weight of one full carton (kg) for the ±8% check.', max_digits=8, null=True),
        ),
    ]
