# Generated by Django 4.2.30 on 2026-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_standard_carton_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fill_volume_liters',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Liters of liquid per bottle (null for powders / multi-brand bundles).', max_digits=8, null=True),
        ),
    ]
