# Generated by Django 4.2.30 on 2026-10-06 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=64)),
                ('driver_name', models.CharField(blank=True, max_length=128)),
                ('helper_name', models.CharField(blank=True, max_length=128)),
                ('production_incharge', models.CharField(blank=True, max_length=128)),
                ('security', models.CharField(blank=True, max_length=128)),
                ('default_challan_no', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('delivered', 'Delivered')], default='planned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip_assignment', to='orders.order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_orders', to='dispatch.trip')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
