# Generated by Django 4.2.30 on 2026-10-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCarton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identical_count', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('deadline_date', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomCartonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_size', models.CharField(choices=[('as_in_catalog', 'As in catalog'), ('5kg_litre_jar', '5 kg / litre jar'), ('1_litre', '1 litre'), ('500_ml', '500 ml'), ('750_ml', '750 ml'), ('250_ml', '250 ml'), ('100_ml', '100 ml'), ('25_ltr_kg_can', '25 Ltr/Kg Can'), ('120_drum', '120 Litre Drum'), ('150_drum', '150 Litre Drum'), ('200_drum', '200 Litre Drum')], default='as_in_catalog', max_length=32)),
                ('qty', models.PositiveIntegerField()),
                ('custom_carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.customcarton')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='customcarton',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cartons', to='orders.order'),
        ),
        migrations.AddField(
            model_name='customcarton',
            name='outer_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.outerbox'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottles', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
