# Generated by Django 4.2.30 on 2026-10-05 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('regular', 'Regular'), ('sample', 'Sample')], max_length=16)),
                ('batch_number', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField()),
                ('ph', models.CharField(blank=True, max_length=64)),
                ('solids', models.CharField(blank=True, max_length=128)),
                ('appearance', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_unit', models.CharField(choices=[('L', 'L'), ('ml', 'ml')], default='L', max_length=8)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, help_text='Remaining volume in liters', max_digits=12)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('qc_result', models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='batches.batchproduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
