# Generated by Django 4.2.30 on 2026-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('material_type', models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('lid', 'Lid'), ('cap', 'Cap'), ('label', 'Label'), ('box', 'Box'), ('partition', 'Partition'), ('pouch', 'Pouch'), ('sticker', 'Sticker'), ('other', 'Other')], default='other', max_length=20)),
                ('purchased_qty', models.PositiveIntegerField(default=0)),
                ('rejected_qty', models.PositiveIntegerField(default=0)),
                ('uip_qty', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
