# Generated by Django 4.2.30 on 2026-10-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('orders', '0001_initial'),
        ('catalog', '0003_loading_clerk_and_product_batch_link'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_no', models.PositiveIntegerField()),
                ('bottles', models.PositiveIntegerField()),
                ('carton_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_sheet_lines', to='batches.batch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_lines', to='dispatch.trip')),
            ],
            options={
                'ordering': ['order_id', 'box_no', 'sort_order', 'id'],
                'unique_together': {('trip', 'order', 'box_no', 'product')},
            },
        ),
    ]
