# Generated by Django 4.2.30 on 2026-10-06 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_loading_clerk_and_product_batch_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingsheetline',
            name='batch',
        ),
        migrations.CreateModel(
            name='ReadyStockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_label', models.CharField(max_length=64)),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ready_stock_lots', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__sort_order', 'product__name', 'batch_label'],
                'unique_together': {('product', 'batch_label')},
            },
        ),
        migrations.AddField(
            model_name='loadingsheetline',
            name='ready_stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_lines', to='loading.readystocklot'),
        ),
        migrations.CreateModel(
            name='BundleComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_set', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bundle_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='catalog.product')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='catalog.product')),
            ],
            options={
                'ordering': ['bundle_product_id', 'sort_order', 'id'],
                'unique_together': {('bundle_product', 'component_product')},
            },
        ),
    ]
