# Generated by Django 4.2.30 on 2026-10-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('loading', '0002_ready_stock_and_sheet_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingsheetline',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_lines', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='readystocklot',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_stock_lots', to='batches.batch'),
        ),
    ]
